### ISSUE TITLE
color.rgbaString is not a function error

### ISSUE THREAD

**Issue by davidmtobias** [fanthos/chartjs-chart-timeline#1]
Hi Fanthos,
First of all, thank you very much for sharing your code, I apreciate it. 
I've noticed a small bug. Just a "color.rgbaString is not a function". I jumped it by deleting "rgbaString()" method call.

https://github.com/fanthos/chartjs-chart-timeline/blob/0ef53274456d3ca3f7cabd97fa5e3baad3933a91/timeline.js#L256

Thanks again,
Have a nice day
David

**Comment by fanthos** [comment]
The callback function `options.colorFunction` should return `Color()` currently. Chart.js has bundled `chartjs-color`.
I think I forgot to change the defaults after changing the code.

**Comment by fairking** [comment]
I had an issue too. I solved it by replacing with:
```
import * as Chart from 'chart.js';
...
colorFunction: function() {
    return Chart.Color('black');
},
```

Probably some of my other modules was using global var `Color` too.
