### ISSUE TITLE
moment alternative?

### ISSUE THREAD

**Issue by balloob** [fanthos/chartjs-chart-timeline#16]
Timeline depends on moment.js for parsing dates. However, moment is a huge dependency!

See here the source map of the vendor bundle for Home Assistant. This bundle only includes Chart.js and the timeline ([source](https://github.com/home-assistant/home-assistant-polymer/blob/master/src/resources/ha-chart-scripts.js)).

Note that we do currently bundle ALL moment locales. 225KB. Stripping out the localses will help but still leaves us 51.53KB for all of moment. 

![image](https://user-images.githubusercontent.com/1444314/40263959-a6dfec8c-5ae8-11e8-9549-0d6daceb1431.png)

Would you be open for this package to use [`fecha`](https://github.com/taylorhakes/fecha) for formatting and [`date-fns`](https://date-fns.org/) for date manipulation? Both are very small utilities.

**Comment by fanthos** [comment]
I like `date-fns`, but `Chart.js` requires `moment` currently. Seems that `date-fns`(25kb when import `format`) is not much smaller than Momentjs on my test.

**Comment by balloob** [comment]
Oh, I didn't realize Chart.js also requires moment. Guess we can stick with that then.
