### ISSUE TITLE
Make NPM compatible

### ISSUE THREAD

**Issue by balloob** [fanthos/chartjs-chart-timeline#9]
Although published to NPM, it still depends on Chart.js being available on the window object. I think that it would make more sense to import chart.js using `import Chart from 'chart.js';`. When bundled with rollup, you can replace that import with `window.Chart` so you can still have an AMD build.

**Comment by fanthos** [comment]
I updated it to `0.2.0`. I think this version should work better.

**Comment by balloob** [comment]
🎉  Thanks !
